#!/bin/bash

# Simple script to enable or disable a PHP version from apache2
echo Enabling a PHP module in Apache2 server...

lib="/etc/apache2/mods-available";
scr=`basename "$0"`;
ver="$1";

if [ -z "$ver" ];
then
    echo "Usage: $scr 5.6|7.0|php5.6|php7.0|..."
    exit;
fi;

phpv="";
if [ -f "$lib/php$ver.conf" ];
then
	phpv="php$ver";

elif [ -f "$lib/$ver.conf" ];
then
	phpv="$ver";
else
	echo "Inavalid php version: $ver";
	exit;
fi;

for file in `ls $lib/php*.conf`
do
	mod=${file:(-11):6}
	sudo a2dismod $mod
done;

sudo a2enmod $phpv
sudo service apache2 restart
echo Apache service restarted...

